export const SIDEBAR_DESKTOP_WIDTH = 180;

export const SIDEBAR_MOBILE_WIDTH = 240;

export const USER_SUGGESTIONS_WIDTH = 240;

export const HEADER_HEIGHT = 60;

export const HOME_PAGE_POSTS_LIMIT = 6;

export const EXPLORE_PAGE_POSTS_LIMIT = 15;

export const PEOPLE_PAGE_USERS_LIMIT = 15;

export const NOTIFICATIONS_PAGE_NOTIFICATION_LIMIT = 50;

export const PROFILE_PAGE_POSTS_LIMIT = 6;

export const MAX_USER_PROFILE_IMAGE_SIZE = 2000000;
