export const MESSAGE_CREATED = "MESSAGE_CREATED";
export const IS_USER_ONLINE = "IS_USER_ONLINE";
export const NEW_CONVERSATION = "NEW_CONVERSATION";
export const NOTIFICATION_CREATED_OR_DELETED =
  "NOTIFICATION_CREATED_OR_DELETED";
export const AUTH_TOKEN_EXPIRY = "1y";
export const RESET_PASSWORD_TOKEN_EXPIRY = 3600000;
